apiVersion: v1
kind: ConfigMap
metadata:
  name: observatory-config
  namespace: observatory
data:
  SPRING_PROFILES_ACTIVE: "k8s"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/observatory_db"
  SPRING_DATA_REDIS_HOST: "redis-service"
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_RABBITMQ_HOST: "rabbitmq-service"
  SPRING_RABBITMQ_PORT: "5672"
---
apiVersion: v1
kind: Secret
metadata:
  name: observatory-secret
  namespace: observatory
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "observatory_secret"
  RABBITMQ_USER: "guest"
  RABBITMQ_PASSWORD: "guest"
  JWT_SECRET_KEY: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
